**Math - Linear Algebra**

*Linear Algebra is the branch of mathematics that studies [vector spaces](https://en.wikipedia.org/wiki/Vector_space) and linear transformations between vector spaces, such as rotating a shape, scaling it up or down, translating it (ie. moving it), etc.*

*Machine Learning relies heavily on Linear Algebra, so it is essential to understand what vectors and matrices are, what operations you can perform with them, and how they can be useful.*

<table align="left">
  <td>
    <a href="https://colab.research.google.com/github/ageron/handson-ml2/blob/master/math_linear_algebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>
  </td>
  <td>
    <a target="_blank" href="https://kaggle.com/kernels/welcome?src=https://github.com/ageron/handson-ml2/blob/master/math_linear_algebra.ipynb"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" /></a>
  </td>
</table>

## Matrices in python
In python, a matrix can be represented in various ways. The simplest is just a list of python lists:

A much more efficient way is to use the NumPy library which provides optimized implementations of many matrix operations:

In [46]:
import numpy as np
import matplotlib as mpl

## Square, triangular, diagonal and identity matrices
A **square matrix** is a matrix that has the same number of rows and columns, for example a $3 \times 3$ matrix:

\begin{bmatrix}
  4 & 9 & 2 \\
  3 & 5 & 7 \\
  8 & 1 & 6
\end{bmatrix}

A matrix that is both upper and lower triangular is called a **diagonal matrix**, for example:

\begin{bmatrix}
  4 & 0 & 0 \\
  0 & 5 & 0 \\
  0 & 0 & 6
\end{bmatrix}

You can construct a diagonal matrix using NumPy's `diag` function:

In [47]:
np.diag([4, 5, 6])

array([[4, 0, 0],
       [0, 5, 0],
       [0, 0, 6]])

If you pass a matrix to the `diag` function, it will happily extract the diagonal values:

In [48]:
D = np.array([
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9],
    ])
np.diag(D)

array([1, 5, 9])

In [49]:
A = np.array([
        [11, 12, 13],
        [14, 15, 16],
        [17, 18, 19],
    ])

Finally, the **identity matrix** of size $n$, noted $I_n$, is a diagonal matrix of size $n \times n$ with $1$'s in the main diagonal, for example $I_3$:

\begin{bmatrix}
  1 & 0 & 0 \\
  0 & 1 & 0 \\
  0 & 0 & 1
\end{bmatrix}

Numpy's `eye` function returns the identity matrix of the desired size:

In [50]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

The identity matrix is often noted simply $I$ (instead of $I_n$) when its size is clear given the context. It is called the *identity* matrix because multiplying a matrix with it leaves the matrix unchanged as we will see below.

The product of a matrix $M$ by the identity matrix (of matching size) results in the same matrix $M$. More formally, if $M$ is an $m \times n$ matrix, then:

$M I_n = I_m M = M$

This is generally written more concisely (since the size of the identity matrices is unambiguous given the context):

$MI = IM = M$

For example:

In [51]:
A.dot(np.eye(3))

array([[11., 12., 13.],
       [14., 15., 16.],
       [17., 18., 19.]])

In [53]:
np.eye(3).dot(A)

array([[11., 12., 13.],
       [14., 15., 16.],
       [17., 18., 19.]])

**Caution**: NumPy's `*` operator performs elementwise multiplication, *NOT* a matrix multiplication:

In [54]:
A * D   # NOT a matrix multiplication

array([[ 11,  24,  39],
       [ 56,  75,  96],
       [119, 144, 171]])

## Matrix transpose
The transpose of a matrix $M$ is a matrix noted $M^T$ such that the $i^{th}$ row in $M^T$ is equal to the $i^{th}$ column in $M$:

$ A^T =
\begin{bmatrix}
  10 & 20 & 30 \\
  40 & 50 & 60
\end{bmatrix}^T =
\begin{bmatrix}
  10 & 40 \\
  20 & 50 \\
  30 & 60
\end{bmatrix}$

In other words, ($A^T)_{i,j}$ = $A_{j,i}$

Obviously, if $M$ is an $m \times n$ matrix, then $M^T$ is an $n \times m$ matrix.

Note: there are a few other notations, such as $M^t$, $M′$, or ${^t}M$.

In NumPy, a matrix's transpose can be obtained simply using the `T` attribute:

In [55]:
A

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [56]:
A.T

array([[11, 14, 17],
       [12, 15, 18],
       [13, 16, 19]])

As you might expect, transposing a matrix twice returns the original matrix:

In [57]:
A.T.T

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

A **symmetric matrix** $M$ is defined as a matrix that is equal to its transpose: $M^T = M$. This definition implies that it must be a square matrix whose elements are symmetric relative to the main diagonal, for example:

\begin{bmatrix}
  17 & 22 & 27 & 49 \\
  22 & 29 & 36 & 0 \\
  27 & 36 & 45 & 2 \\
  49 & 0 & 2 & 99
\end{bmatrix}

The product of a matrix by its transpose is always a symmetric matrix, for example:

In [58]:
D.dot(D.T)

array([[ 14,  32,  50],
       [ 32,  77, 122],
       [ 50, 122, 194]])

From:

https://numpy.org/doc/stable/reference/generated/numpy.linalg.inv.html?highlight=inverse

In [69]:
A = np.array([[1., 2.], [3., 4.]])

In [70]:

from numpy.linalg import inv
Ainv = inv(A)
Ainv

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [71]:
Ainv.dot(A)

array([[1.0000000e+00, 4.4408921e-16],
       [0.0000000e+00, 1.0000000e+00]])

Why this result?

In [72]:
A.dot(Ainv)

array([[1.00000000e+00, 1.11022302e-16],
       [0.00000000e+00, 1.00000000e+00]])

from
https://numpy.org/doc/stable/reference/generated/numpy.linalg.det.html

In [73]:
from numpy.linalg import det
det(A)

-2.0000000000000004

In [74]:
B = np.array([[1., 2.], [1., 2.]])

In [75]:
det(B)

0.0

In [ ]:
inv(B)